[tool.poetry]
name = "hashstore"
version = "0.7.0"
description = "HashStore, a hash-based object store for data packages."
authors = ["Matt Jones <gitcode@magisa.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
hashfs = "^0.7.2"
pathlib = "^1.0.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
